name: ECR Build and Push
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: main
      SERVICE_NAME: a-container-ecr

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Build docker image
      - name: Image Build
        run: |-
          docker build -t 781797606691.dkr.ecr.us-east-1.amazonaws.com/chamod-demo/$SERVICE_NAME:latest .

      # Push image to Elastic Container Registry
      - name: Image Push
        run: |-
          docker push 781797606691.dkr.ecr.us-east-1.amazonaws.com/chamod-demo/$SERVICE_NAME:latest
